### ISSUE TITLE
glTF-pbrMetallicRoughness': undeclared identifier 'UNITY_DISPLAY_ORIENTATION_PRETRANSFORM'

### ISSUE THREAD

**Issue by mrgbell** [atteneder/glTFast#626] opened 2023-07-03 20:02 UTC
Running Unity 2021.3.12f1 with URP 12.1.7 building for Android 10.0 (API level 29)
glTFast version: 5.0.4

After completing the Shader Loading steps from the instructs and when trying to build for Android I run into this error:

Shader error in 'Shader Graphs/glTF-pbrMetallicRoughness': undeclared identifier 'UNITY_DISPLAY_ORIENTATION_PRETRANSFORM' at Files/Unity/Hub/Editor/2021.3.12f1/Editor/Data/CGIncludes/UnityCG.cginc(817) (on vulkan)

Compiling Subshader: 2, Pass: BuiltIn Forward, Vertex program with DIRECTIONAL VERTEXLIGHT_ON _ADDITIONAL_LIGHTS _MAIN_LIGHT_SHADOWS_CASCADE _SCREEN_SPACE_OCCLUSION _SHADOWS_SOFT
Platform defines: SHADER_API_MOBILE UNITY_ASTC_NORMALMAP_ENCODING UNITY_ENABLE_REFLECTION_BUFFERS UNITY_LIGHTMAP_RGBM_ENCODING UNITY_NO_CUBEMAP_ARRAY UNITY_NO_FULL_STANDARD_SHADER UNITY_NO_RGBM UNITY_NO_SCREENSPACE_SHADOWS UNITY_PASS_FORWARDBASE UNITY_PBS_USE_BRDF3 UNITY_PRETRANSFORM_TO_DISPLAY_ORIENTATION
Disabled keywords: DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON FOG_EXP FOG_EXP2 FOG_LINEAR INSTANCING_ON LIGHTMAP_ON LIGHTMAP_SHADOW_MIXING LIGHTPROBE_SH SHADER_API_GLES30 SHADOWS_SCREEN SHADOWS_SHADOWMASK UNITY_COLORSPACE_GAMMA UNITY_ENABLE_DETAIL_NORMALMAP UNITY_ENABLE_NATIVE_SHADOW_LOOKUPS UNITY_FRAMEBUFFER_FETCH_AVAILABLE UNITY_HALF_PRECISION_FRAGMENT_SHADER_REGISTERS UNITY_HARDWARE_TIER1 UNITY_HARDWARE_TIER2 UNITY_HARDWARE_TIER3 UNITY_LIGHTMAP_DLDR_ENCODING UNITY_LIGHTMAP_FULL_HDR UNITY_LIGHT_PROBE_PROXY_VOLUME UNITY_METAL_SHADOWS_USE_POINT_FILTERING UNITY_NO_DXT5nm UNITY_PBS_USE_BRDF1 UNITY_PBS_USE_BRDF2 UNITY_SPECCUBE_BLENDING UNITY_SPECCUBE_BOX_PROJECTION UNITY_UNIFIED_SHADER_PRECISION_MODEL UNITY_USE_DITHER_MASK_FOR_ALPHABLENDED_SHADOWS UNITY_VIRTUAL_TEXTURING _ADDITIONAL_LIGHTS_VERTEX _ADDITIONAL_LIGHT_SHADOWS _ADDITIONAL_OFF _EMISSIVE _MAIN_LIGHT_SHADOWS _MAIN_LIGHT_SHADOWS_SCREEN _OCCLUSION _TEXTURE_TRANSFORM _TRANSMISSION

**Comment by bruce-vermeer** [comment] 2023-07-31 20:22
+1, also running into this issue

**Comment by ssmore101** [comment] 2023-08-27 07:58
+2 same issue

**Comment by ssmore101** [comment] 2023-08-27 07:58
cannot convert from 'struct v2f_surf' to 'struct SurfaceDescription'

**Comment by GitHubUsername1** [comment] 2023-12-15 19:05
+3 i have this issue too.

**Comment by atteneder** [comment] 2024-08-09 10:05
I couldn't reproduce with Unity 2021.3.42f1, URP 12.1.15 and glTFast 6.7.1, so I recommend upgrading and I'm closing this one.

There's a chance that I've missed a shader variant that causes the issue. If the problem pops up again, please re-open the issue.

Thanks for reporting!

**Closed by atteneder** 2024-08-09 10:05 UTC
Labels: bug
