### ISSUE TITLE
Material is not imported and the object is rendered pink.

### ISSUE THREAD

**Issue by burakkaraceylan** [atteneder/glTFast#369] opened 2022-03-16 08:30 UTC
**Describe the bug**
The material is not imported using the 4.6.0 version but it works fine with 4.5.0 with the standard pipeline. It renders the oject pink since no material is applied.

**Files**
https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF/Duck.gltf

**To Reproduce**
var gltf = gameObject.AddComponent<GLTFast.GltfAsset>();
gltf.url = "https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Duck/glTF/Duck.gltf";

**Expected behavior**
It should import the asset together with the material.

**Desktop (please complete the following information):**
 - glTFast version4 4.6.0
 - Unity Editor version 2020.3.25f
 - Render Pipeline and version  Standart Render Pipeline
 - Platform: Editor

**Comment by atteneder** [comment] 2022-04-20 15:13
@burakkaraceylan Thanks for reporting and your patience.

I could not reproduce it.
It does not even work in the Editor? Or is it in builds only?
Maybe it's your project's setup. Can you provide a simple reproduction project?

**Comment by burakkaraceylan** [comment] 2022-04-20 19:37
No worries! Thanks for the amazing work!

It didn't work in the editor and in the webgl build. The scene was the standart empty Unity scene. Since then we upgraded Unity to 2020.3.31f1 and everything have been working fine in this version with glTFast 4.6.0.

**Comment by atteneder** [comment] 2022-04-21 08:05
@burakkaraceylan That's great to hear!

I'm going to close it now, but feel free to re-open if you ever run into this problem again.

Thanks!

**Closed by atteneder** 2022-04-21 08:05 UTC
Labels: bug, question
