### ISSUE TITLE
Interrupt leading to "A Native Collection has not been disposed, resulting in a memory leak. "

### ISSUE THREAD

**Issue by Din-Wan** [atteneder/glTFast#210] opened 2021-07-09 02:31 UTC
Hi, newbie here, I want to support cancelling the loading of a model in my project. I am aware that cancellation is not supported yet, so I'm currently okay with the load completing and doing nothing, but i'm running into a error. I create an instance of GltfImport inside my Requester class and then start the load operation. If a "cancellation" occurs, I want to be able to create a new Requester and load a model again. However, if I do that, sometimes I end up with an error related to a NativeArray not being disposed.

My code looks a bit like this:
```
public async void Request(string url) {
	var gltfImport = new GltfImport();
	loadSuccessful = await gltfImport.Load(url);

	if (loadSuccessful && !requestCancelled)
	{
		MessageManager.Instance.SendMessage(this, "success", gltfImport, RequestComplete);
	}
	else
	{
		if (requestCancelled)
			return;
		MessageManager.Instance.SendMessage(this, message, null, RequestComplete);
	}
}
```

These are the errors I am getting:
``` 
A Native Collection has not been disposed, resulting in a memory leak. Allocated from:
Unity.Collections.NativeArray`1:.ctor(Int32, Allocator, NativeArrayOptions)
GLTFast.VertexBufferConfig`1:ScheduleVertexJobs(VertexInputData, Nullable`1, Nullable`1, VertexInputData[], Nullable`1, Nullable`1, Nullable`1) (at Library\PackageCache\com.atteneder.gltfast@4.0.1\Runtime\Scripts\VertexBufferConfig.cs:72)
GLTFast.<LoadAccessorData>d__110:MoveNext() (at Library\PackageCache\com.atteneder.gltfast@4.0.1\Runtime\Scripts\GltfImport.cs:1968)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<LoadAccessorData>d__110&)
GLTFast.GltfImport:LoadAccessorData(Root)
GLTFast.<Prepare>d__99:MoveNext() (at Library\PackageCache\com.atteneder.gltfast@4.0.1\Runtime\Scripts\GltfImport.cs:1184)
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
```
```
A Native Collection has not been disposed, resulting in a memory leak. Allocated from:
Unity.Collections.NativeArray`1:.ctor(Int32, Allocator, NativeArrayOptions)
GLTFast.VertexBufferTexCoords`1:ScheduleVertexUVJobs(VertexInputData[], NativeSlice`1) (at Library\PackageCache\com.atteneder.gltfast@4.0.1\Runtime\Scripts\VertexBufferTexCoords.cs:51)
GLTFast.VertexBufferConfig`1:ScheduleVertexJobs(VertexInputData, Nullable`1, Nullable`1, VertexInputData[], Nullable`1, Nullable`1, Nullable`1) (at Library\PackageCache\com.atteneder.gltfast@4.0.1\Runtime\Scripts\VertexBufferConfig.cs:181)
GLTFast.<LoadAccessorData>d__110:MoveNext() (at Library\PackageCache\com.atteneder.gltfast@4.0.1\Runtime\Scripts\GltfImport.cs:1968)
System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1:Start(<LoadAccessorData>d__110&)
GLTFast.GltfImport:LoadAccessorData(Root)
GLTFast.<Prepare>d__99:MoveNext() (at Library\PackageCache\com.atteneder.gltfast@4.0.1\Runtime\Scripts\GltfImport.cs:1184)
System.Runtime.CompilerServices.MoveNextRunner:InvokeMoveNext(Object)
```

Any tips or guidance would be greatly appreciated.

**Comment by atteneder** [comment] 2021-11-23 16:26
Yes, glTFast needs to become interruptible. Currently its behavior is not reliable.

**Comment by atteneder** [comment] 2022-06-01 14:47
Duplicate of #177 . Closing.

**Closed by atteneder** 2022-06-01 14:47 UTC
Labels: bug
