### ISSUE TITLE
Unity 2022.2 - Normal maps are not interpreted correctly on Android when player settings use the default DXT5nm encoding

### ISSUE THREAD

**Issue by benpurdy** [atteneder/glTFast#553] opened 2023-01-04 18:41 UTC
When the platform is set to Android, normal maps are not interpreted correctly when "Normal map encoding" value is set to DXT5nm in the player settings.  This seems to be an issue in newer versions of Unity as I see this happen with 2022.2.1f1 but it does not occur in Unity 2021.3.7f1.

I have attached two screenshots illustrating the difference when changing the "Normal map encoding" value from "DXT5nm-style" to "XYZ". The "XYZ" encoding looks correct, the "DXT5nm-style" encoding looks incorrect.

1. Create a project in Unity 2022.2.1f1 and import the GLTFast library.
2. In the Build Settings window, change the platform to "Android"
3. Add a GLTF asset to the project which includes normal maps.
4. Add the GLTF asset to the scene.
6. Observe the GLTF model, the reflected skybox will look strange and sort of "inside-out"
7. Open Project Settings -> Player -> Android Settings -> Other Settings
8. Change the "Normal Map Encoding" option to "XYZ"
9. Observe the GLTF model, the reflected skybox will look correct.

**Expected behavior**

The GLTFast import/loading logic should respect the current normal map encoding settings when loading normal maps.

**Screenshots**

Here is the bug, when "normal map encoding" is set to DXT5nm-style 

<img width="565" alt="Incorrect - normal map encoding set to dxt5nm" src="https://user-images.githubusercontent.com/1986498/210626050-17c6e8dd-72fc-4d0c-8799-df1b9ded42e5.png">

Here is the same asset with "normal map encoding" set to XYZ

<img width="632" alt="Correct - normal map encoding set to XYZ" src="https://user-images.githubusercontent.com/1986498/210626052-95abdaaa-db24-4a57-9ef8-1ef903cad39e.png">

**Desktop**
 - gltFast version 5.0.0
 - Unity Editor 2022.2.1f1
 - Editor running on Mac, platform set to Android

**Comment by atteneder** [comment] 2024-12-12 14:06
duplicate of #694

**Closed by atteneder** 2024-12-12 14:06 UTC
Labels: bug
