### ISSUE TITLE
It does not support KHR_lights_punctual？

### ISSUE THREAD

**Issue by LIMr1209** [atteneder/glTFast#414] opened 2022-06-06 09:31 UTC
**Describe the bug**

**Files**

Attach or link to *.gltf/*.glb files that trigger the bug. 

In addition, make sure to run those files through the [glTF Validator](https://github.khronos.org/glTF-Validator) first. If you encounter errors or warnings, try to make sure they are not responsible for the issue and file a bug report with the software that generated the glTF file as well.

> Note: You have to ZIP archive them first in order for GitHub to accept the upload.

If your files are confidential:

- Try to create a similar, but intellectual-property-free glTF that reproduces the bug in the same way (so any community member can have a look)
- Otherwise, still create this issue and send the files (or a link to them) discretely via email

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - glTFast version
 - Unity Editor version [e.g. 2021.2.1f1]
 - Render Pipeline and version [e.g. Universal Render Pipeline 12.0]
 - Platform: [e.g. Editor, Windows Player, iOS]
 
additionally (if significant for the bug):

 - For WebGL: Browser [e.g. stock browser, safari]

**Additional context**

**Comment by atteneder** [comment] 2022-06-07 08:06
Duplicate of #17 

Tips for opening GitHub issues:

1. Search if there already is a similar issue. If there is one, subscribe to it, comment on it, but do not open another one
2. If you open an issue, provide the information asked for (or delete non-relevant sections of the pre-filled form). I wouldn't expect devs to spend much time on an issue if the submitter wouldn't spend time on making a proper description.

Lastly: This feature is close to be finished. See branch [lights-punctual](https://github.com/atteneder/glTFast/tree/lights-punctual)

**Closed by atteneder** 2022-06-07 08:06 UTC
Labels: bug
