### ISSUE TITLE
Importer not combining meshes 

### ISSUE THREAD

**Issue by friuns2** [atteneder/glTFast#412] opened 2022-06-03 11:49 UTC
Currently importer generates extra nodes instead of loading combined mesh with combined materials
![image](https://user-images.githubusercontent.com/16543239/171847639-41be5a19-cb76-4423-b465-a966a6f52455.png)

There shouldn't be CombinedMesh_LOD0_1 its should be part of CombinedMesh_LOD
[660043.zip](https://github.com/atteneder/glTFast/files/8832067/660043.zip)

**Comment by atteneder** [comment] 2022-06-03 12:09
Duplicate of #153 

Unfortunately no near-term updates planned.

**Closed by atteneder** 2022-06-03 12:09 UTC
Labels: enhancement
