### ISSUE TITLE
How to Extract Material?

### ISSUE THREAD

**Issue by butaixianran** [atteneder/glTFast#349] opened 2022-03-02 15:52 UTC
Imported gltf turned into a prefab without a Extract Material button.

The "Extract from prefab" menu also is gray, not available.

Then how can I Extract Materials from it? I need to modify those materials.

I'm using standard pipeline with Unity 2021.2

**Comment by atteneder** [comment] 2022-03-02 16:48
This is not implemented yet.

workaround: Expand glTF in project view, duplicate sub-assets, tweak them and re-assign manually.

Duplicate of #305

**Closed by atteneder** 2022-03-02 16:48 UTC
