### ISSUE TITLE
Material Appearance Discrepancy between Windows and Android on glTFast

### ISSUE THREAD

**Issue by wangyanmeego** [atteneder/glTFast#673] opened 2024-02-04 07:10 UTC
## Description
There is a noticeable difference in the appearance of materials when viewing them on Windows versus Android platforms using glTFast. On Windows, the materials appear correctly. However, on Android, it looks like there's a layer of fog over the object's surface, which is not intended and differs from the expected rendering.

## Steps to Reproduce
1. Import a glTF model using glTFast in a Unity project.
2. Build and run the application on a Windows machine.
3. Observe the material rendering, which appears correct.
4. Build and run the same application on an Android device.
5. Notice the difference in material appearance, resembling a foggy overlay on the object's surface.

the image on windows:
![gltfast-rendering-in-windows](https://github.com/atteneder/glTFast/assets/13783955/e1ca5b6b-9201-4499-83d4-6f85c15bd4c3)

the image on Android:
![gltfast-rendering-in-android](https://github.com/atteneder/glTFast/assets/13783955/d5068762-272d-4167-b674-642554b981a7)

**Comment by wangyanmeego** [comment] 2024-02-04 07:29
Test on glTFast 5.0.0 and glTFast 6.0.1，Rendering Pipeline is URP 12.

**Comment by wangyanmeego** [comment] 2024-02-06 01:31
Finally, I found the cause of the problem and tried methods to solve it. It was caused by normal map sampling, we were using the SampleTexture2D node to sample the normal map texture, which was not a problem in Windows, but would cause errors when switching to the Android platform, this should be a bug of Unity. I tried to change the node for sampling the normal map texture from SampleTexture2D to NormalFromTexture, and the result was that there was no problem.
![image](https://github.com/atteneder/glTFast/assets/13783955/da2ed89c-9938-43bf-948c-4211139100cd)

**Comment by atteneder** [comment] 2024-06-26 22:31
Hi,

Is it possible that you've been using [DXTnm normal map encoding](https://docs.unity3d.com/ScriptReference/NormalMapEncoding.DXT5nm.html) on Android? That would certainly explain the problem, as glTF normal maps are always XYZ.

See #553

**Comment by atteneder** [comment] 2024-12-16 11:01
I assume that DXTnm is the cause and close this one in favor of #694.

**Closed by atteneder** 2024-12-16 11:01 UTC
Labels: bug
