### ISSUE TITLE
glTFast conflict issue

### ISSUE THREAD

**Issue by alessandroperetti** [atteneder/glTFast#522] opened 2022-11-28 10:34 UTC
Hi,

I have a unity project with glTFast library installed (last version).
I installed the SocketIOUnity inside my project in order to use websocket.

Whenever the installation process has finished I got all the scripts recompilation in Unity with a console error:

```Library/PackageCache/com.atteneder.gltfast@f6c014e6b0/Runtime/Scripts/GltfImport.cs(410,13): error CS0518: Predefined type 'System.IAsyncDisposable' is not defined or imported```

I think there is a conflict between SocketIOUnity and gltfast somehow.

How can I solve the issue?

Thanks,

Al

**Comment by atteneder** [comment] 2022-11-28 10:37
Duplicate of #514 

I'll look into it today

**Closed by atteneder** 2022-11-28 10:37 UTC
Labels: bug
