### ISSUE TITLE
.glb model exported from 3ds max and cinema4d doesn't import in runtime

### ISSUE THREAD

**Issue by omidhedayati** [atteneder/glTFast#660] opened 2023-11-30 20:07 UTC
@atteneder Hello,

I have been using a GLB model exported from Blender, and everything looks great. However, I encountered an issue when trying to use 3ds Max and Cinema4D for exporting models. I found that I cannot import these models at runtime. Could you please clarify if glTFast supports models exported from 3ds Max and Cinema4D? Any guidance on this would be greatly appreciated.

Thank you for your assistance.

**Comment by atteneder** [comment] 2024-06-26 22:25
Hi @omidhedayati ,

I don't have neither of those tools at hand, so I'm kindly asking you to:

1. Check your glTFs in [Khronos Sample Viewer](https://github.khronos.org/glTF-Sample-Viewer-Release/) and/or [Don's glTF Viewer](https://gltf-viewer.donmccurdy.com/) and see if they load and look correctly there. Don's viewer comes with glTF validation built-in, which gives you extra details.
2. Share test models that fail to load with glTFast directly in this issue, so I can have a look.

Thanks!

**Comment by atteneder** [comment] 2024-12-16 13:15
Closing due to lack of reproduction material.

**Closed by atteneder** 2024-12-16 13:15 UTC
Labels: bug
