### ISSUE TITLE
Meta Quest Browser Failed to import runtime GLBs

### ISSUE THREAD

**Issue by SantinoCasolati-Legend** [atteneder/glTFast#655] opened 2023-11-01 19:07 UTC
**Describe the bug**
Webgl export on PC works as expected. GLTFast.GltfImport Load function always returns false in meta quest browser and cannot load the file

**To Reproduce**
var gltfMeshes = new GLTFast.GltfImport();
var successMeshes = await gltfMeshes.Load(url);

And successMeshes is always false

**Expected behavior**
To return true and load the file in meta quest browser

**Desktop (please complete the following information):**
 - glTFast version:  6.0.1
 - Unity Editor version: 2022.3.8f1
 - Render Pipeline and version: Built In
 - Platform: WebGL
 
additionally (if significant for the bug):

 - Device: Meta Quest 2
 - For WebGL: Meta Quest Browser

**Comment by atteneder** [comment] 2024-06-15 13:18
Thanks for reporting.

Unfortunately I don't have that device at hands. 

1. Please use a custom [logger](https://docs.unity3d.com/Packages/com.unity.cloud.gltfast@6.6/api/GLTFast.Logging.ICodeLogger.html) (e.g. the ConsoleLogger), pass it into the constructor of `GltfImport` and analyze its messages.
2. Please test your project in another browser and let me know if it's reproducible there (including steps)
3. Can you provide a sample glTF file that triggers said error?

Thanks

**Comment by atteneder** [comment] 2024-12-16 15:54
Closing due to lack of detailed information.

**Closed by atteneder** 2024-12-16 15:54 UTC
Labels: bug
