### ISSUE TITLE
Point Cloud Rendering issue

### ISSUE THREAD

**Issue by EricBeetsOfficial-Opuscope** [atteneder/glTFast#399] opened 2022-05-11 16:30 UTC
**Describe the bug**
I try to load a model (based on point cloud from sketchfab) in runtime, and I have a rendering issue and logs warnings on iOS (in Editor mode, I just have log warnings)

```
Drawing with MeshTopology.Points, yet the vertex program 'Shader Graphs/glTF-unlit-Opaque-double' does not have PSIZE output.
Drawing with MeshTopology.Points, yet the vertex program 'Shader Graphs/glTF-unlit-Opaque-double' does not have PSIZE output.
Drawing with MeshTopology.Points, yet the vertex program 'Shader Graphs/glTF-unlit-Opaque-double' does not have PSIZE output.
Drawing with MeshTopology.Points, yet the vertex program 'Shader Graphs/glTF-unlit-Opaque-double' does not have PSIZE output.
Drawing with MeshTopology.Points, yet the vertex program 'Shader Graphs/glTF-unlit-Opaque-double' does not have PSIZE output.
Drawing with MeshTopology.Points, yet the vertex program 'Shader Graphs/glTF-unlit-Opaque-double' does not have PSIZE output.
Drawing with MeshTopology.Points, yet the vertex program 'Shader Graphs/glTF-unlit-Opaque-double' does not have PSIZE output.
```

**To Reproduce**
Load the model in runtime.

```
var importer = new GltfImport(..)
bool success = await importer.Load(fileName);
...
   GameObjectBoundsInstantiator insta = new GameObjectBoundsInstantiator(gltfAsset.importer, transform, null);
   importer.InstantiateMainScene(insta);
...

```
**Expected behavior**
I guess, the rendering would be the same  on Editor

**Screenshots**

On Editor (correct rendering):
![Screenshot 2022-05-11 at 18 12 32](https://user-images.githubusercontent.com/63807677/167897434-9a80c5fe-4596-46b9-ab16-2910b9e69aae.png)

On device (wrong rendering)
https://user-images.githubusercontent.com/63807677/167896939-5cba581c-1fad-4a22-be81-66636cba5d26.mp4

**Desktop (please complete the following information):**
 - glTFast: 4.6.0
 - Unity Editor: 2021.2.27f1
 - Render Pipeline: URP 11.0
 - Platform: iOS
 
Maybe I made something wrong ..
Thanks in advance (and thank you for the great job !!)

Eric

**Comment by atteneder** [comment] 2022-06-01 09:31
Closing. Duplicate of #246

**Closed by atteneder** 2022-06-01 09:31 UTC
Labels: bug, help wanted
