### ISSUE TITLE
Oculus Destroy Issue

### ISSUE THREAD

**Issue by Jeorgey** [atteneder/glTFast#709] opened 2024-08-06 15:21 UTC
I have glb files I'm trying to load through a URL or Streaming assets both ways work on windows and on the Unity editor problem is on the oculus build the oculus tries loading it then destroys both the URL and streaming asset versions.

[Uploading NBcomp.zip…]()

**Expected behavior**
Loads normally as in the editor or windows [version.](![image_2024-08-06_181428522](https://github.com/user-attachments/assets/a7747eea-c942-4e91-876d-3981fd082523))

**Screenshots**
![image_2024-08-06_181749246](https://github.com/user-attachments/assets/470e1488-b8b6-468c-aafd-5a9487cecbfe)

**Desktop**
 - glTFast version: 5.0.0
 - Unity Editor version [2022.3.16f1]
 - Render Pipeline and version: Default pipeline
 - Platform: Android
  - Device: Meta Quest 2

**Oculus Log**
14:45:42.074
Resources
Preloaded drawable resource #0x1080288 (android:drawable/dialog_background_material) that varies with configuration!!
14:46:47.699
Unity
at GLTFast.GltfImport..ctor (GLTFast.Loading.IDownloadProvider downloadProvider, GLTFast.IDeferAgent deferAgent, GLTFast.Materials.IMaterialGenerator materialGenerator, GLTFast.Logging.ICodeLogger logger) [0x00000] in <00000000000000000000000000000000>:0
14:46:47.699
Unity
at GLTFast.GltfAssetBase.Load (System.String gltfUrl, GLTFast.Loading.IDownloadProvider downloadProvider, GLTFast.IDeferAgent deferAgent, GLTFast.Materials.IMaterialGenerator materialGenerator, GLTFast.Logging.ICodeLogger logger) [0x00000] in <00000000000000000000000000000000>:0
14:46:48.004
Unity
at GLTFast.GltfImport..ctor (GLTFast.Loading.IDownloadProvider downloadProvider, GLTFast.IDeferAgent deferAgent, GLTFast.Materials.IMaterialGenerator materialGenerator, GLTFast.Logging.ICodeLogger logger) [0x00000] in <00000000000000000000000000000000>:0
14:46:48.004
Unity
at GLTFast.GltfAssetBase.Load (System.String gltfUrl, GLTFast.Loading.IDownloadProvider downloadProvider, GLTFast.IDeferAgent deferAgent, GLTFast.Materials.IMaterialGenerator materialGenerator, GLTFast.Logging.ICodeLogger logger) [0x00000] in <00000000000000000000000000000000>:0
14:46:47.699
Unity
at GLTFast.GltfAssetBase.Load (System.String gltfUrl, GLTFast.Loading.IDownloadProvider downloadProvider, GLTFast.IDeferAgent deferAgent, GLTFast.Materials.IMaterialGenerator materialGenerator, GLTFast.Logging.ICodeLogger logger) [0x00000] in <00000000000000000000000000000000>:0
14:46:47.699
Unity
at GLTFast.GltfAssetBase.Load (System.String gltfUrl, GLTFast.Loading.IDownloadProvider downloadProvi
14:46:48.004
Unity
at GLTFast.GltfAssetBase.Load (System.String gltfUrl, GLTFast.Loading.IDownloadProvider downloadProvider, GLTFast.IDeferAgent deferAgent, GLTFast.Materials.IMaterialGenerator materialGenerator, GLTFast.Logging.ICodeLogger logger) [0x00000] in <00000000000000000000000000000000>:0
14:46:48.004
Unity
at GLTFast.GltfAssetBase.Load (System.String gltfUrl, GLTFast.Loading.IDownloadProvider downloadProvi
14:48:05.544
[SEO] ModelDef
Destroying ModelFileModel guardianLaserBeam.gltf.ovrscene
14:48:05.545
[SEO] ModelDef
Destroying ModelFileModel pinchArrowBlend.gltf.ovrscene
14:48:05.546
[SEO] ModelDef
Destroying ModelFileModel guardianLaserBeam.gltf.ovrscene
14:48:05.547
[SEO] ModelDef
Destroying ModelFileModel pinchArrowBlend.gltf.ovrscene

**Comment by atteneder** [comment] 2024-09-04 10:19
Hi,

hard to tell. I wasn't able to download your glb file. Could you try to upload it again?

It might just be that the file is gigantic and too much to handle for the device?

Let's see.

**Comment by atteneder** [comment] 2024-12-18 11:36
Closing due to lack of information on how to reproduce.

**Closed by atteneder** 2024-12-18 11:36 UTC
Labels: bug
