### ISSUE TITLE
Glb with KHR_mesh_quantization appears black

### ISSUE THREAD

**Issue by JSWorkspace1** [atteneder/glTFast#288] opened 2021-12-01 15:50 UTC
**Describe the bug**
Model with KHR_mesh_quantization appears black. 
I have two models that should be identical except one uses KHR_mesh_quantization.

In an [Online Viewer](https://gltf-viewer.donmccurdy.com/) they look identical .
![Screenshot 2021-12-01 160013](https://user-images.githubusercontent.com/23420842/144259916-0f437ee8-c6f4-45fb-bf10-bc631055fea6.png)

But when loaded via gltfFast they look like this ( model with quantization on the left) 
![Screenshot 2021-12-01 155638](https://user-images.githubusercontent.com/23420842/144261181-0e76d58b-3e96-43a9-b778-534e79175498.png)

**Files**
[GLBModels.zip](https://github.com/atteneder/glTFast/files/7634975/GLBModels.zip)

**Desktop;**
 - glTFast version 4.4.7
 - Unity Editor version 2020.3.23f1
 - Platform: Windows 10

**Comment by atteneder** [comment] 2021-12-01 16:28
Hi @JSWorkspace1 ,

Thanks for reporting. Are you using the built-in render pipeline? Does the shading become correct if you scale up the whole model?

This is likely a duplicate of #75. A probable solution could be increasing the precision of the vertex-to-fragment data types, but I don't know if that has performance impact.

**Comment by JSWorkspace1** [comment] 2021-12-02 09:00
Yes using the standard render pipeline.
Yes between 6-7x Scale lighting becomes normal. 

This issue could be closed since its already tracked.

**Comment by atteneder** [comment] 2021-12-15 18:22
I'm closing this now, since it's a duplicate of #75

Please see the original for updates

**Closed by atteneder** 2021-12-15 18:22 UTC
Labels: bug

**Comment by blanxdev** [comment] 2022-01-28 16:07
> Hi @JSWorkspace1 ,
> 
> Thanks for reporting. Are you using the built-in render pipeline? Does the shading become correct if you scale up the whole model?
> 
> This is likely a duplicate of #75. A probable solution could be increasing the precision of the vertex-to-fragment data types, but I don't know if that has performance impact.

Hi, can you please give a bit more details where to change this?

I am also experiencing the shading problems and wanted to see if this helps.

Thanks

**Comment by atteneder** [comment] 2022-01-29 20:05
> Hi, can you please give a bit more details where to change this?

Sorry, there's no solution for this atm. Again, this is a duplicate. The situation is explained in detail in #75.

You can circumvent this by switching to Universal Render Pipeline or not using quantization.
