### ISSUE TITLE
Regression: some URP shaders have too many variants in 2021.2

### ISSUE THREAD

**Issue by hybridherbst** [atteneder/glTFast#269] opened 2021-11-05 13:43 UTC
**Describe the bug**
Not sure if this is a regression in URP or in glTFast, I believe the former is more likely.
When adding the glTFast shaders to the list of "Always included" shaders, building to Android on 2021.2.0f1 fails with the error message:
```Shader Graphs/glTF-metallic-Premultiply-double has too many Shader variants(201326592).To resolve this, go to Project Settings > Graphics and remove this Shader from the Always Included Shaders list.For more explicit control over how Unity includes specific Shader variants in a build, use a ShaderVariantCollection.```

As the goal for the glTFast shaders would indeed be to be always included (so that all models can be loaded), I think this is a blocker for using glTFast for runtime loading on 2021.2 right now.

**To Reproduce**
1. make a project on 2021.2 with URP targeting Android
2. add the glTFast shadergraph shaders to the list of always included shaders
3. try to build

**Expected behavior**
Building works, actually error message prevents building

**Comment by atteneder** [comment] 2021-11-05 14:07
Thanks for reporting...that's a real bummer :/

Let's brainstorm solutions:

- Splitting up shader by certain shader keyword (GAMMA would be a good candidate, since you never need both linear and gamma workflow variants)
- Convert certain shader keywords into properties (downside is additional complexity in final shader code and thus a chance of performance impact)

On top of that an Editor tools/script that auto-generates a sane sub-set of variants based on your required material features. Even if a project needs to deal with all features, certain combinations are unlikely ever used (e.g. emissive, occluded and transmissive at the same time).

[This artice][1] might be useful.
Imho the problem is less glTF(ast) specific, but more generic (interesting read about this is shader permutations [part 1][2] and [part 2][3])

Let me know your thoughts.

[1]: https://blog.unity.com/technology/stripping-scriptable-shader-variants
[2]: https://therealmjp.github.io/posts/shader-permutations-part1/
[3]: https://therealmjp.github.io/posts/shader-permutations-part2/

**Comment by hybridherbst** [comment] 2021-11-05 14:11
I actually think it needs to be fixed in Core, as it seems that shader stripping is applied _after_ checking for Always Included shaders.
Reported to Unity as (Case 1378545) [Shaders][URP][Regression] Build is prevented with shaders in Always Included list

**Comment by hybridherbst** [comment] 2021-11-05 14:29
For reference,

![shaders_2020 3_all](https://user-images.githubusercontent.com/2693840/140526608-4bce7d16-8749-4fb1-83c1-5eedb647909f.png)   
![shaders_2020 3_skip-unused](https://user-images.githubusercontent.com/2693840/140526621-cf201db3-e009-4d30-9613-c7522ac22245.png)   
**2020.3**   

![shaders_2021 2-all](https://user-images.githubusercontent.com/2693840/140526638-b76d5955-c878-4cce-b09c-132c87b47b6b.png)   
![shaders_2021 2-skip-unused](https://user-images.githubusercontent.com/2693840/140526646-cfe76e5b-c2af-4410-9e37-f3e511005c2e.png)   
**2021.2**

**Comment by atteneder** [comment] 2021-11-10 16:39
Note: While debugging other material problems (transparency/blending in HDRP >=10) I noticed that some material features that used to require a separate shader graph can now be controlled via shader keywords. That might be helpful for this issue as well.

**Comment by hybridherbst** [comment] 2021-11-10 20:45
Yes, that and also since ShaderGraph supports Built-In starting with 2021.2 the added complexity of those shaders also goes away.

**Comment by atteneder** [comment] 2021-12-21 18:42
@hybridherbst  Looking at it!

Strangely I couldn't reproduce it (glTFast 4.4.9, Unity 2021.2.7f1 with URP 12.1.2). I now ticked off "strip unused variants" in URP's global settings and now I have to wait a while :)

Here's the [Unity issue](https://issuetracker.unity3d.com/issues/some-lit-shaders-are-having-huge-count-of-variants-which-leads-to-project-build-prevention)

**Comment by atteneder** [comment] 2022-01-24 16:41
@hybridherbst Is this still a problem? glTFast 4.5.0 uses less shader graph versions. We should re-evaluate this issue.

**Comment by ROBYER1** [comment] 2022-01-26 16:24
I was relived to remove a lot of variants when using URP 12 with gltFast 4.5.0+, keeping an eye on build times here to see if there is a big improvement

**Comment by hybridherbst** [comment] 2022-01-27 09:21
I think the underlying issue still isn't fixed in Unity though (it's still in [the "Known Issues" list ](https://unity3d.com/de/unity/whats-new/2021.2.8#:~:text=ShaderGraph%3A%20Some%20lit%20Shaders%20are%20having%20huge%20count%20of%20variants%20which%20leads%20to%20project%20build%20prevention%20(1378545))of Really Bad Things In Releases)

It might just be under the one million variants it needs to be to pass the broken check now, I'll also try that out

@ROBYER1 the issue isn't that that all these many variants where actually built, it's that Unity did first check how many could potentially be there, and abort if that was too many, instead of counting and checking after stripping. 
(still of course build times might go down a bit with full glTFast shader builds with less variants!)

**Comment by ROBYER1** [comment] 2022-01-27 09:33
I noticed the same issue with Unity also. The only benefit I had was in Unity 2021.2 with GLTFast 4.5.* and URP 12 I didn't have to use so many legacy variants. 

Keeping an eye on this as you with the aborting during builds if I slapped all the variants in rather than just the ones I use so I got lucky in our app use case.

**Comment by hybridherbst** [comment] 2022-01-27 10:04
Thing is, if you want to load generic glTF models at runtime (e.g. you don't know what users will add) you definitely want to include the entire set of glTFast shaders as always included ones - otherwise some models will look wrong. Fingers crossed that Unity actually fixes this soon...

**Comment by pzhine** [comment] 2022-05-03 17:21
Unity allows me to build with all of the glTFast shaders included, but it takes a long time (30-40 min on a fast machine). Does anyone know where Unity puts the built shaders, so I can archive those files and just drop them into subsequent builds? I'm building for iOS and Android...

**Comment by hybridherbst** [comment] 2022-05-03 17:33
Subsequent builds will reuse the shaders on the same machine, they're getting cached directly into the Library. Only the first build on a machine (or when you changed the shaders) should take this long.

**Comment by pzhine** [comment] 2022-05-03 19:36
Actually, if I don't check "Scripts Only Build" they get compiled every time.

**Comment by hybridherbst** [comment] 2022-05-03 21:25
That would be a bug, please report that to Unity. It doesn't matter if "Scripts Only" is on or not, compiled shaders will be cached unless your disk is full. Shader stripping though will not be cached (but shouldn't take excessively long - if it does, still please report a bug).

**Comment by pzhine** [comment] 2022-05-04 11:27
Ok, thanks, I will file a bug. For reference, it is the "Preparing variants for compilation" that takes forever.
<img width="512" alt="Screenshot 2022-05-04 at 13 26 37" src="https://user-images.githubusercontent.com/2692844/166672711-96eea727-55a8-46ed-83ef-c7cf86a80a38.png">

**Comment by hybridherbst** [comment] 2022-05-04 11:41
Yeah, I believe that's a known issue in 2021.2 with URP since they added a ton of multi_compile debug variants that all need to be stripped away at build time and that's not efficient / not cached currently. Can't hurt to report another bug

**Comment by pzhine** [comment] 2022-05-05 19:31
Done! https://fogbugz.unity3d.com/default.asp?1425665_8e8453tjnsmolq17

**Comment by pzhine** [comment] 2022-07-21 10:18
Everyone who is struggling with this bug, please vote for the fix here: https://issuetracker.unity3d.com/issues/ios-shaders-are-recompiled-on-subsequent-builds

**Comment by atteneder** [comment] 2022-12-15 16:52
Closing, since this was [fixed](https://issuetracker.unity3d.com/issues/some-lit-shaders-are-having-huge-count-of-variants-which-leads-to-project-build-prevention) by the URP devs:

> It's now fixed in Universal RP 12.1.5 (2021.2.14f1), 13.1.6 (2022.1.0b10), 14.0.2 (2022.2.0a9), and above.

**Closed by atteneder** 2022-12-15 16:52 UTC
Labels: bug
