### ISSUE TITLE
How to use ECS system on gltfast?

### ISSUE THREAD

**Issue by IvanMax3212** [atteneder/glTFast#214] opened 2021-07-14 05:28 UTC
Nowadays, I am working with large size GLB files for architectural rendering.
But with standalone rendering with several occlusion culling systems, I couldn't upgrade the FPS. 
So I want to convert the all materials to entity and use hybrid rendering system on them.
But I couldn't find codes which create entities instead of gameobjects in this repository.
Also to use Hybrid Renderer v2 I have to use this in HDRP project.
But the publisher only used the built -in simple HDRP material in that case.
Is there anyone who can solve my issue? 

Kind regards, Andranik

**Comment by atteneder** [comment] 2021-07-14 07:18
Hi @IvanMax3212 ,

Thanks for your interest! Unfortunately I haven't looked into support for ECS (see #92 ) or Hybrid Rendering yet. There have been pull requests #94 and #95, which seem to be a first step. However, they came very soon (wrt the maturity of this project) and so I decided to park them for the moment.

DOTS is definitely interesting, but I cannot promise a solution before fall.

hth

Closing as duplicate of #92

**Closed by atteneder** 2021-07-14 07:18 UTC
