### ISSUE TITLE
Export - Export in a single glb file

### ISSUE THREAD

**Issue by Pourfex** [atteneder/glTFast#562] opened 2023-01-25 10:22 UTC
**Is your feature request related to a problem? Please describe.**
The runtime export of GLTFast provides a .bin and a .glb 
If I want to load the result later in the app or in other apps, I would need to merge them in a single .zip file or a .glb file (as many don't succeed to load the .bin - actually only mccurdy gltf viewer succeed to do it).

**Describe the solution you'd like**
The export should result in a single .glb file without the .bin file. Or there should be an option to do so.

**Describe alternatives you've considered**
Merge the .bin and .glb, make a zip file and load it.

**Comment by atteneder** [comment] 2023-01-30 16:33
@Pourfex  Have your followed the [runtime export documentation](https://github.com/atteneder/glTFast/blob/main/Documentation%7E/ExportRuntime.md)?

What does your export code look like?

**Comment by Pourfex** [comment] 2023-01-31 07:57
@atteneder Yeah I just followed the exemple as is.
`
        var exportSettings = new ExportSettings {
            Format = GltfFormat.Binary,
            FileConflictResolution = FileConflictResolution.Overwrite,
        };
        
        var export = new GameObjectExport( exportSettings);
        
        export.AddScene(rootLevelNodes, "My new glTF scene");
       
        // path is something like streaming assets / test.glb   
        var success = await export.SaveToFileAndDispose(path);
`

I was expecting a single glb file instead of glb + bin file.

**Comment by atteneder** [comment] 2024-09-04 13:41
I cannot reproduce. Could you provide a full scene that reproduces the problem?

**Comment by atteneder** [comment] 2024-12-12 20:09
Closing due to lack of reproduction instructions.

**Closed by atteneder** 2024-12-12 20:09 UTC
Labels: enhancement
