### ISSUE TITLE
Missing textures  when export GLB on URP

### ISSUE THREAD

**Issue by Phantomxm2021** [atteneder/glTFast#420] opened 2022-06-27 08:22 UTC
**Describe the bug**
Missing textures when export GLB to file on URP 
<img width="718" alt="image" src="https://user-images.githubusercontent.com/82647748/175892136-fdeb465d-7c0e-4562-b691-2995a7673b16.png">
<img width="694" alt="image" src="https://user-images.githubusercontent.com/82647748/175892876-9af1ff52-3b32-4111-aea8-34c4b4c17927.png">

**Files**
[DamagedHelmet.glb](https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/DamagedHelmet/glTF-Binary/DamagedHelmet.glb)

**To Reproduce**
1. Load the DamagedHelmet.glb
2. Right click 'export'
3. drop and drag into Unity editor

**Desktop (please complete the following information):**
 - glTFast version [4.7.0]
 - Unity Editor version [2021.3.5f1]
 - Render Pipeline and version [Universal Render Pipeline 12.1.7]
 - Platform: [Editor]

**Comment by atteneder** [comment] 2022-06-27 12:41
Hi @Phantomxm2021 ,

duplicate of #385

It is considered etiquette to first search in existing issues before raising a new one. In this case it even uses the exact same test model ˆˆ

Thanks

**Closed by atteneder** 2022-06-27 12:41 UTC
Labels: bug
