### ISSUE TITLE
Runtime import: Convert to URP/Lit based materials

### ISSUE THREAD

**Issue by Phlicess** [atteneder/glTFast#376] opened 2022-04-01 09:25 UTC
When importing glTF in the Runtime,  I want to change gltf default material to URP/Lit or my custom material.
I see the info in document:
![image](https://user-images.githubusercontent.com/11753644/161235664-079a1082-d9f0-442e-b16d-c0f2d22ea512.png)

so, What is the best way? (。-ω-)zzz

**Comment by atteneder** [comment] 2022-04-08 09:27
@Phlicess Yes, that's the way to go!

If you manage to write and submit a first draft of a `Lit` material generator, I'd be happy to review and include it!

Closing, since this is a duplicate of #258 

Thanks!

**Closed by atteneder** 2022-04-08 09:27 UTC
Labels: enhancement
