### ISSUE TITLE
Animation cannot loop when using GltfImport with 'mecanim'  settings

### ISSUE THREAD

**Issue by edwinhan1983** [atteneder/glTFast#662] opened 2023-12-12 09:59 UTC
I tried to download a glb with animations using GltfImport with 'mecanim'  settings by code in runtime, then would use AnimatorOverrideController to change old animation clip to this new animation clip.  (I can not use 'legacy' settings because  legacy animation clip is not working with AnimatorOverrideController in unity).

Everything works fine except the animation can not loop even with 'WrapMode.Loop' configured. 

I did find a similar record here: https://github.com/atteneder/glTFast/issues/291, but the manually editing method is not very suitable for my case, is there any new changes that we can change the animation clip to loop through runtime code?

thanks.

**Comment by atteneder** [comment] 2024-08-09 09:14
Thanks for reporting.

Fist, Mecanim is not tested at runtime, only the legacy animation system is.

Could you please provide a small code sample (or entire project) so I can reproduce it easily?

**Comment by atteneder** [comment] 2024-12-16 13:14
Closing due to lack of details.

**Closed by atteneder** 2024-12-16 13:14 UTC
Labels: enhancement
