### ISSUE TITLE
Under Android platform, the gltf model that loads local files will have the wrong path.

### ISSUE THREAD

**Issue by han-tianyu** [atteneder/glTFast#667] opened 2024-01-16 07:02 UTC
[new Uri(uri, ".")] in UriHelper.GetBaseUri(Uri uri) cannot process files in the jar:file:// path, and an error message is displayed.
It is recommended to change GetBaseUri(Uri uri) to
`
public static Uri GetBaseUri(Uri uri)
        {
            return GetParentUri(uri, 1);
        }
`
and
`
public static Uri GetParentUri(Uri uri, int level)
        {
            if (uri == null) return null;
            string[] segments = uri.Segments;
            string uriString = uri.Scheme + ":";
            if (!string.IsNullOrEmpty(uri.Host))
            {
                uriString += "//" + uri.Host;
            }
            if (segments.Length >= level)
            {
                string parentDirectory = String.Join("", segments, 0, segments.Length - level).Replace("//", "/");
                uriString += parentDirectory;
            }
            return new Uri(uriString, UriKind.RelativeOrAbsolute);
        }
`

**Comment by atteneder** [comment] 2024-09-06 15:35
I was able to reproduce the issue. It's the combination of double-schema (`jar:file:`) and a (escaped) unicode character that causes problems. Since the double-schema is used on Android only, it only surfaced there.

**Comment by atteneder** [comment] 2024-12-11 10:19
fixed in 6.9.0.

**Closed by atteneder** 2024-12-11 10:19 UTC
Labels: bug
